name: joker_state
description: "A Flutter Style lightweight state management package."
version: 1.0.0
homepage:

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
