name: joker_state
description: > 
  Joker is a lightweight, reactive state management solution for Flutter that
  brings the fun of the circus to your codebase with simple, flexible, and
  type-safe state handling.
version: 3.1.1
homepage: https://github.com/Aykahshi/joker_state
repository: https://github.com/Aykahshi/joker_state

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  circus_ring: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
