name: joker_state
description: > 
  Joker is a lightweight, reactive state management solution for Flutter that
  brings the fun of the circus to your codebase with simple, flexible, and
  type-safe state handling.
version: 4.2.0+1
homepage: https://github.com/Aykahshi/joker_state
repository: https://github.com/Aykahshi/joker_state

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  circus_ring: ^1.0.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter