name: clean_architecture_example
description: A minimal clean architecture example using joker_state wirte by Cursor AI.

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  # Use the joker_state package from the parent directory
  joker_state:
    path: ../../ # Relative path to the root where joker_state source is

dev_dependencies:
  flutter_test:
    sdk: flutter

# It's important that the example uses the local version of joker_state
# for testing purposes, hence the path dependency. 